name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install Node.JS
        uses: actions/setup-node@v3
        with:
          check-latest: true
          cache: 'yarn'

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.1'

      - name: Install Javascript dependencies
        run: yarn install --immutable

      - name: FE build cache cache
        uses: actions/cache@v3
        with:
          path: |
            tmp/cache
          key: ${{ runner.os }}-builder-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-builder-cache-

      - name: Run rubocop linter
        run: bundle exec rubocop

      - name: Run eslint linter
        run: yarn lint

      - name: Run tests for GO parser
        run: go test -v
        working-directory: wasm_parser/parser

      - name: Run tests for GO inliner
        run: go test -v
        working-directory: wasm_inliner/inliner

      - name: Compile WASM parser
        run: bundle exec rake wasm:parser

      - name: Compile WASM inliner
        run: bundle exec rake wasm:inliner

      - name: Build website
        run: bundle exec middleman build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
